@startuml
class ExerciseTimerPage {
    + ExerciseTimerPage(pageManager:PageManager)
    + View() : void
    + Run() : void
    + SetMsg(msg:string) : void
    + RefreshMsg(msg:string) : void
    + GetDataModel() : JSONModelHandler<ExerciseModel>
}
IPageAdapter <|-- ExerciseTimerPage
@enduml
