@startuml
!include .\.\app\Program.puml
!include .\core\App.puml
!include .\core\PageManager.puml
!include .\core\Quotes.puml
!include .\models\BMIModel.puml
!include .\models\ExerciseModel.puml
!include .\models\IModelAdapter.puml
!include .\models\JSONModelHandler.puml
!include .\models\MoodModel.puml
!include .\models\TodoModel.puml
!include .\pages\BMIPage.puml
!include .\pages\ExerciseTimerPage.puml
!include .\pages\HabitTodoPage.puml
!include .\pages\HomePage.puml
!include .\pages\IPageAdapter.puml
!include .\pages\MoodTracker.puml
!include .\pages\ReportPage.puml
!include .\utils\Constants.puml
!include .\utils\IFileReader.puml
!include .\utils\IFileWriter.puml
!include .\utils\JSONFileReader.puml
!include .\utils\JSONFileWriter.puml
!include .\pages\choices\ChoiceBackToHome.puml
!include .\pages\choices\ChoiceManager.puml
!include .\pages\choices\ChoiceNavigatePage.puml
!include .\pages\choices\IChoiceAdapter.puml
!include .\pages\choices\BMIPageChoice\AddBMIRecord.puml
!include .\pages\choices\BMIPageChoice\DeleteBMIRecord.puml
!include .\pages\choices\ExerciseTimerChoice\DeleteExerciseRecord.puml
!include .\pages\choices\ExerciseTimerChoice\StartTimer.puml
!include .\pages\choices\MoodPageChoice\AddMoodRecord.puml
!include .\pages\choices\MoodPageChoice\DeleteMoodRecord.puml
!include .\pages\choices\TodoPageChoice\AddTodo.puml
!include .\pages\choices\TodoPageChoice\DeleteTodo.puml
!include .\pages\choices\TodoPageChoice\UpdateTodo.puml
@enduml
