@startuml
class MoodModel {
    + MoodModel()
    + ToDict() : Dictionary<string, List<string>>
    + AddRecord(index:string, value:List<string>) : void
    + RemoveRecord(key:string) : bool
    + Update(key:string, newValue:List<string>) : bool
    + {static} GetAllMoods() : List<string>
    + SetData(newRecords:Dictionary<string, List<string>>) : void
}
IModelAdapter <|-- MoodModel
@enduml
