@startuml
class TodoModel {
    + TodoModel()
    + ToDict() : Dictionary<string, List<string>>
    + AddRecord(index:string, value:List<string>) : void
    + RemoveRecord(key:string) : bool
    + Update(key:string, newValue:List<string>) : bool
    + {static} GetAllStatus() : List<string>
    + SetData(newRecords:Dictionary<string, List<string>>) : void
}
IModelAdapter <|-- TodoModel
@enduml
